server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://106.55.173.219:13306/b_filmBuy?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false #关闭缓存
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

    #整合redis
  redis:
    host: 106.55.173.219
#    host: 10.0.100.4
    port: 13377
    database: 1
    lettuce:
      pool:
        max-active: 1000
        max-idle: 500
        max-wait: 500
    timeout: 5000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.entity

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

authority:
  info: '[{"models":[{"modelId":1,"operation":[1,2,3,4]},{"modelId":1000001,"operation":[1,2,3,4]},{"modelId":1000003,"operation":[1,2,3,4]},{"modelId":2,"operation":[1,2,3,4]},{"modelId":3,"operation":[1,2,3,4]},{"modelId":4,"operation":[1,2,3,4]},{"modelId":10000014,"operation":[1,2,3,4]},{"modelId":1000015,"operation":[1,2,3,4]},{"modelId":1000016,"operation":[1,2,3,4]},{"modelId":1000017,"operation":[1,2,3,4]},{"modelId":1000018,"operation":[1,2,3,4]}],"level":1,"modelId":1,"name":"管理员"},{"models":[{"modelId":1000001,"operation":[4]},{"modelId":1000003,"operation":[4]},{"modelId":2,"operation":[4]},{"modelId":4,"operation":[4]},{"modelId":10000014,"operation":[4]},{"modelId":1000015,"operation":[4]},{"modelId":1000016,"operation":[4]},{"modelId":1000017,"operation":[4]},{"modelId":1000018,"operation":[4]}],"level":2,"modelId":3,"name":"用户"}]'

logging:
  file: log/my.log

web:
  upload-path: d:/myfile/upload
  front-path: d:/myfile/front




